/* - - - - -  Bought - - - - - */

SELECT ITM.ITEM_CODE, ITM.ITEM_NAME, RTI.STORE_KEY, PRODUCT_TYPE, STYLE, COUNTRY_STATE,
CASE
    WHEN (RTI.[Price]  < 15) THEN 'Under15'
    WHEN (RTI.[Price] >= 15 AND RTI.[Price] < 25) THEN 'Under25'        
    WHEN (RTI.[Price] >= 26 AND RTI.[Price] < 40) THEN 'Under40'
WHEN (RTI.[Price] >= 40) THEN 'Over40'       
ELSE 'Under25'
END AS PRICERANGE
FROM [EDAP_ITEM] ITM
INNER JOIN [EDAP_ITEMSTORE_REALTIMEINVENTORY] RTI ON ITM.ITEM_CODE = RTI.ITEM_CODE
INNER JOIN [HybrisImageURLs_Target] IMG ON ITM.ITEM_CODE = IMG.ItemCode
WHERE RTI.SALES_STRATEGY IN ('NB')
AND ITM.DEPARTMENT = 'WINE'
AND RTI.INVENTORY > 10
AND RTI.PRICE > 5
AND RTI.PRICE < 100
AND IMG.Image_140x196 IS NOT NULL
AND RTI.WEB_APPROVED = 1
AND PRODUCT_TYPE IS NOT NULL
AND STYLE IS NOT NULL
AND COUNTRY_STATE IS NOT NULL



/* - - - - -  Shown - - - - - */

SELECT 
ITM.ITEM_CODE, ITM.ITEM_NAME, ITM.PRODUCT_TYPE, ITM.STYLE, ITM.COUNTRY_STATE,
RTI.STORE_KEY, SUM(TLI.SALES_DOLLARS) as SUMOFSALES,
CASE
    WHEN (RTI.[Price]  < 15) THEN 'Under15'
    WHEN (RTI.[Price] >= 15 AND RTI.[Price] < 25) THEN 'Under25'        
    WHEN (RTI.[Price] >= 26 AND RTI.[Price] < 40) THEN 'Under40'
WHEN (RTI.[Price] >= 40) THEN 'Over40'       
ELSE 'Under25'
END AS PRICERANGE
FROM [EDAP_ITEM] ITM
INNER JOIN [EDAP_ITEMSTORE_REALTIMEINVENTORY] RTI ON ITM.ITEM_CODE = RTI.ITEM_CODE
INNER JOIN [HybrisImageURLs_Target] IMG ON ITM.ITEM_CODE = IMG.ItemCode
INNER JOIN [EDAP_TRANSACTIONLINEITEM_LASTYEAR] TLI ON TLI.ITEM_CODE = ITM.ITEM_CODE
WHERE RTI.SALES_STRATEGY IN ('WD','WP')
AND ITM.DEPARTMENT = 'WINE'
AND RTI.INVENTORY > 10
AND RTI.PRICE > 5
AND RTI.PRICE < 100
AND IMG.Image_140x196 IS NOT NULL
AND RTI.WEB_APPROVED = 1
AND ITM.PRODUCT_TYPE IS NOT NULL
AND ITM.STYLE IS NOT NULL
AND ITM.COUNTRY_STATE IS NOT NULL
GROUP BY ITM.ITEM_CODE, ITM.ITEM_NAME, RTI.STORE_KEY, ITM.PRODUCT_TYPE, ITM.STYLE, ITM.COUNTRY_STATE, RTI.PRICE




/* - - - - -  Item Matching - - - - - */

SELECT NB.ITEM_CODE AS NBItemCode, WD.ITEM_CODE AS WDItemCode, NB.STORE_KEY, WD.SUMOFSALES AS SumOfSalesWD
FROM [AT038NBWineItems_Bought] NB
INNER JOIN [AT038WDWineItems_Shown] WD
    ON NB.PRODUCT_TYPE = WD.PRODUCT_TYPE
    AND NB.STYLE = WD.STYLE
    AND NB.COUNTRY_STATE = WD.COUNTRY_STATE
    AND NB.STORE_KEY = WD.STORE_KEY



/* - - - - -  NB Items with enough matches - - - - - */

SELECT NBItemCode, Store_Key, Count(NBItemCode) AS CountWDMatches FROM [AT038ItemMatching]
GROUP BY NBItemCode, Store_Key
HAVING COUNT(NBItemCode) >= 3



/* - - - - -  Receivedinlast45 - - - - - */

SELECT SubscriberKey FROM [AT038SendLog]
WHERE SendDate >= DateAdd(day,-45,GetDate())



/* - - - - -  Purchased NB Items with matches - - - - - */

SELECT SS.SubscriberKey, SS.EmailAddress, SS.PriceZone, SS.PreferredStore, SS.[Loyalty Number], NB.NBItemCode
FROM [Sendable_Subscribers] SS
INNER JOIN [EDAP_TransactionLineItem_LastYear] TLI on TLI.LOYALTY_CARD_NUM = SS.[Loyalty Number]
INNER JOIN [AT038NBItemsWithEnoughMatches] NB on TLI.Item_Code = NB.NBItemCode AND TLI.Store_Key = NB.Store_key
WHERE TLI.Business_Date >= DateAdd(day,-9,GetDate())
AND TLI.Business_Date <= DateAdd(day,-7,GetDate())






