SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-720,GetDate())
AND Business_Date < DateAdd(day,-690,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-690,GetDate())
AND Business_Date < DateAdd(day,-660,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-660,GetDate())
AND Business_Date < DateAdd(day,-630,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-630,GetDate())
AND Business_Date < DateAdd(day,-600,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-600,GetDate())
AND Business_Date < DateAdd(day,-570,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-570,GetDate())
AND Business_Date < DateAdd(day,-540,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-540,GetDate())
AND Business_Date < DateAdd(day,-510,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-510,GetDate())
AND Business_Date < DateAdd(day,-480,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-480,GetDate())
AND Business_Date < DateAdd(day,-450,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-450,GetDate())
AND Business_Date < DateAdd(day,-420,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-420,GetDate())
AND Business_Date < DateAdd(day,-390,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-390,GetDate())
AND Business_Date < DateAdd(day,-360,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-360,GetDate())
AND Business_Date < DateAdd(day,-330,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-330,GetDate())
AND Business_Date < DateAdd(day,-300,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-300,GetDate())
AND Business_Date < DateAdd(day,-270,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-270,GetDate())
AND Business_Date < DateAdd(day,-240,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-240,GetDate())
AND Business_Date < DateAdd(day,-210,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-210,GetDate())
AND Business_Date < DateAdd(day,-180,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-180,GetDate())
AND Business_Date < DateAdd(day,-150,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-150,GetDate())
AND Business_Date < DateAdd(day,-120,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-120,GetDate())
AND Business_Date < DateAdd(day,-90,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-90,GetDate())
AND Business_Date < DateAdd(day,-60,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-60,GetDate())
AND Business_Date < DateAdd(day,-30,GetDate())


SELECT LOYALTY_CARD_NUM, EMAIL_ADDR, TXN_ID, STORE_KEY, SALES_CHANNEL, TXN_LINE_ITEM, ITEM_CODE, ITEM_POSITION, ITEM_POSITION_NAME, TOTAL_UNIT_SALES_QUANTITY, ITEM_UNIT_PRICE, ORIG_UNIT_PRICE, SALES_DOLLARS, COUPON_DISCOUNT, NON_COUPON_DISCOUNT, AWARD_DISCOUNT, COUPON_USED, DISCOUNT_USED, AWARD_USED, BUSINESS_DATE FROM [EDAP_TransactionLineItem]
WHERE Business_Date >= DateAdd(day,-30,GetDate())
